pull_request_rules:
  - name: need owners approvals to merge PR
    conditions: 
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "approved-reviews-by=nb-ohad"
    actions:
      merge:
        method: merge
  - name: add draft label to draft PR
    conditions:
      - "draft=true"
    actions:
      label:
        add:
          - draft
