pull_request_rules:
  - name: ping owners for review
    conditions: 
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "approved-reviews-by=nb-ohad"
    actions:
      merge:
        method: merge
