# permissions for end users to edit managedfusionofferings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedfusionoffering-editor-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - managedfusionofferings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - managedfusionofferings/status
  verbs:
  - get
