# permissions for end users to view managedfusionofferings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedfusionoffering-viewer-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - managedfusionofferings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - managedfusionofferings/status
  verbs:
  - get
