---
name: image-builder

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - uses: actions/checkout@v3

      - name: Build operator docker image
        run: make docker-build