---
name: image-builder

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: export go-version
        run: export GO_VERSION=`grep -m 1 -r "go" go.mod | awk '{print $2}'`
        env:
          GO_VERSION: ${{ env.GO_VERSION }} 
        
      - name: print GO_VERSION
        run: echo $GO_VERSION

      - uses: actions/setup-go@v3
        with:
          go-version: $GO_VERSION

      - name: Build operator docker image
        run: make docker-build