---
name: image-builder

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: export go-version
        run: echo "GO_VERSION=$(grep -m 1 -r 'go' go.mod | awk '{print $2}')" >> $GITHUB_ENV
        
      - name: print go-version
        run: echo $GO_VERSION

      - name: setting test var
        run: test=test1

      - name: print test var
        run: echo $test

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build operator docker image
        run: make docker-build